accepted/005-wagtail-api-fields.rst

Addition to #5
Similar to the way the * shortcut adds all fields to the response. This commit adds the _ shortcut, which removes all fields from the response.
Developers who know the fields they need could use this to remove the overhead of having to send all the default field data.

API v2 "no fields shortcut"

---

draft/018-meta-fields.md
draft/xxx-meta-fields.md

[Rendered](https://github.com/wagtail/rfcs/blob/meta-fields/draft/018-meta-fields.md)
We are currently designing an REST API for creating and updating pages. This will be used by external editing applications and may also be used within the Wagtail admin interface as well.
There is a group of fields on the ``Page`` model that are [ignored by revisions](https://github.com/wagtail/wagtail/blob/da067679cdd7999c256c8916f78c82f7641d51cd/wagtail/wagtailcore/models.py#L1423-L1441). They're ignored to prevent any unwanted side-effects happening if that revision is viewed or restored later on.
This RFC proposes that we replace the "meta" section of pages in the API with this set of fields. Initially, this will apply to the admin API only, but could also become the default for the public API as …

RFC 18: Admin API - Meta fields

---

000-template.md
README.md

This PR adds documentation of the RFC process into the readme. Our process is already very similar to what is used by [Rust](https://github.com/rust-lang/rfcs), [EmberJS](https://github.com/emberjs/rfcs) and [Yarn](https://github.com/yarnpkg/rfcs) so I've based it on the wording used by EmberJS (which is itself based on Rust RFCs).

Document RFC process in README.md

---

text/035-sub-teams.md

[Rendered](https://github.com/wagtail/rfcs/blob/sub-teams/text/035-sub-teams.md)

RFC 35: Sub teams

---

text/042-data-transfer-between-installations.md

[Rendered](https://github.com/gasman/weps/blob/81060c34c190482e262be6b7595ac4d213276704/text/042-data-transfer-between-installations.md)

RFC 42: Data transfer between Wagtail installations

---

text/043-author-locking.md
text/xxx-author-locking.md

[Rendered](https://github.com/wagtail/rfcs/blob/author-locking/text/043-author-locking.md)
This RFC proposes some changes we can make to the page locking behaviour to make it more useful.
Currently, users with the "Lock" permission can lock a page to prevent anyone (including the user who locked the page) from editing it.
This feature was originally developed for the RCA to allow student pages to be locked after they have been reviewed by an administrator (this was to prevent the student from editing the page again before it was published as all student pages were published on the same day). It has also been used as a way to prevent editors from editing the index page of section they should only have permission to add/edit subpages.
The main proposal in this RFC is to change this …

RFC 43: Author specific page locking

---

README.md
text/010-search-query-classes.md
text/011-revisions-api.md
text/015-revisions-api-revised.md
text/025-search-query-classes-revised.md
text/029-immutable-revision-events.md

Closes #61
- Restore text of RFC 11
- Add notes about deletion and supersession to RFCs #10, #11, #29 (restored file for 29)
- Make links functional in RFCs #15 and #25
- Update links to RFCs in README to use "Active" and "Proposed" labels (which I just made, and which make it easier to browse the PRs by sorting out PRs like this one which aren't RFCs)

[#61] Note obsolete PRs rather than deleting them

---

text/065-listblock.md
text/xxx-listblock.md

[Rendered](https://github.com/wagtail/rfcs/blob/listblock/text/065-listblock.md)

RFC 65: Adding UUIDs into ListBlock

---

text/000-commenting.md
text/050-commenting.md

[Rendered](https://github.com/jacobtoppm/rfcs/blob/commenting/text/050-commenting.md)

RFC 50: Commenting in the Wagtail Editor

---

text/046-simple-rich-text.md

[Rendered](https://github.com/wagtail/rfcs/blob/simple-rich-text/text/046-simple-rich-text.md)
This is an outline proposal for a new field and block type which would behave like a ``RichTextField``/``RichTextBlock`` but only allows a single segment of text.
Inline elements such as formatting and hyperlinks may be allowed. But block elements like paragraphs, images and bullet points will not. The HTML segment in the database will not be enclosed in a `<p>` tag giving developers more flexibility in where it can be used.
I think this will be very useful for:
- Introductions/summaries which can usually only be one paragraph but use rich text fields as they may need inline formatting. For example, the sentence above "Tom Dyson" in https://wagtail.io/blog/wagtail-2-7/.
- Image captions
- Inline …

Outline RFC 46: Single paragraph rich text fields/blocks

---

README.md

This change updates the README to improve the links to RFCs. We haven't been consistently using the "Proposed" and "Active" GitHub labels and so the current links don't provide a good overview of what RFCs are still under discussion
and which ones have been accepted by the core team and are awaiting implementation.

Improve links to open and active RFCs

---

text/084-2023-roadmap.md

[Rendered](https://github.com/thibaudcolas/rfcs/blob/rfc-84-2023-roadmap/text/084-2023-roadmap.md)
Follow-up to #79, defining more of the roadmap process (reviewing additions via RFCs), as well as proposing specific items for the next three releases.

RFC 84: Public roadmap updates

---

text/085-snippets-parity-modeladmin.md

[Rendered](https://github.com/laymonage/rfcs/blob/rfc-85-modeladmin-parity-for-snippets/text/085-snippets-parity-modeladmin.md)
Follow up to the [Snippets vs ModelAdmin parity discussion](https://github.com/wagtail/wagtail/discussions/10206), as I think using an RFC is easier for reviewing each individual customisation point described in the discussion.
Note that some of the items in the RFC have been implemented and merged into `main` (PRs are linked). However, it is likely that some of the customisations need a clearer implementation plan, hence the RFC. These features may not make it into the next release (5.0 at the time of writing), so this RFC can still be useful for future reference.
I highly recommend giving the code of the current `SnippetViewSet` class a read: …

RFC 85: Snippets parity with ModelAdmin

---

text/088-roadmap-updates.md

Ahead of the Wagtail 6.0 release :) [View the rendered RFC](https://github.com/thibaudcolas/rfcs/blob/88-roadmap-updates/text/088-roadmap-updates.md).

RFC #88: Public roadmap updates

---

text/091-roadmap-updates.md

Preparing for Wagtail 6.1\* – see also RFCs #88 and #86. [View the rendered RFC](https://github.com/thibaudcolas/rfcs/blob/91-roadmap-updates/text/091-roadmap-updates.md).
I have changed the format a bit again, to hopefully make this easier to review. There is:
- One section reviewing what happens with all items currently in v6.0
- One section with all items proposed for v6.1\*, including the ones that are already scheduled as such.
- One section with all items proposed for v6.2\*
---
With the proposal here,
- We’d mark 10 out of 11 items in the v6.0 release as "Done"
- We’d have 7 items in the upcoming v6.1\* May 2024 release (one carry-over, one "continuation of last release")
- We’d have 2 items scheduled for the v6.2\* August 2024 release
- No items would move to "Future"

RFC #91 roadmap updates

---

text/098-roadmap-updates.md

[View the RFC in HTML](https://github.com/thibaudcolas/rfcs/blob/98-roadmap-updates/text/098-roadmap-updates.md).
As discussed in this week’s core team, this is coming in a bit late, and with only 4 items scheduled for the v6.2 August 2024 release, so we have a better chance to hit 100% completion of everything on the roadmap for the next release.
Aside from the items on the roadmap, during this release cycle there’s also been lots of work on DjangoCon Europe, Wagtail Space NL, Wagtail Space US. And we can’t formally commit but there’s interest in working on:
- Telepath refactoring discovery (prep for [Auto-save support refactorings with Telepath](https://github.com/wagtail/roadmap/issues/47))
- StreamField frontend validation (min/max etc)
- Page editor: Minimap UI and blocks collapsed …

RFC 98: roadmap updates

---

text/095-concurrent-editing-notifications.md

[Rendered view](https://github.com/wagtail/rfcs/blob/2d29384f4b8c3e8a6138764482c42cce2d15355e/text/095-concurrent-editing-notifications.md)
Currently, if two users edit the same page or snippet at the same time, the second user to save their changes will overwrite the first user's changes. This doesn't seem to be a common problem, and can often be avoided through communication - however, it will need to be addressed in advance of implementing auto-saving, as this increases the likelihood of users overwriting each other's changes unknowingly.
The "holy grail" of avoiding edit conflicts would be a real-time collaborative editing feature where changes are reflected immediately on the other user's screen, but this will not happen any time soon. A locking mechanism has been proposed, but this …

RFC 95: Concurrent editing notifications

---

text/103-roadmap-updates.md

[View the RFC in HTML](https://github.com/thibaudcolas/rfcs/blob/103-roadmap-updates/text/103-roadmap-updates.md). Once reviewed with enough feedback and approved by the core team, those changes will go live on the [Wagtail Roadmap](https://wagtail.org/roadmap/).
6.4\*: Provisional version number.
---
Back in #102 we provisionally added quite a few items for v6.4, and have been able to make enough plans ahead of time to keep them to schedule (in particular [StreamField Block UI Enhancements: Drag & Drop, Copy/Paste, Styling and Previews #12354](https://github.com/wagtail/wagtail/discussions/12354)). So the changes in this RFC are pretty minimal.

RFC #103: Wagtail 6.4* roadmap updates

---

text/106-roadmap-updates.md

[View the RFC in HTML](https://github.com/thibaudcolas/rfcs/blob/106-roadmap-updates/text/106-roadmap-updates.md). Once reviewed with enough feedback and approved by the core team, those changes will go live on the [Wagtail Roadmap](https://wagtail.org/roadmap/).
6.5\* and 6.6\*: Provisional version numbers. See our [Release schedule](https://github.com/wagtail/wagtail/wiki/Release-schedule) for more info.

RFC #106: Wagtail 6.5* and 6.6* roadmap updates

---

text/105-site-setting-permissions.md

[Rendered](https://github.com/wagtail/rfcs/blob/9837ec834a8f47fe9af933e4317f553cbae96cfe/text/105-site-setting-permissions.md)
Currently, permissions on [site settings](https://docs.wagtail.org/en/stable/reference/contrib/settings.html) are governed by a standard global Django permission record on the model, meaning that users have edit permission for the settings of all sites, or none. This does not fit well with organisational structures where a member of staff has overall responsibility for one particular site. This RFC proposes a new permission model where groups can be assigned permissions at the level of individual sites.

RFC 105: Site setting permissions

---

text/104-validation-on-publish.md

[Rendered](https://github.com/wagtail/rfcs/blob/272e6bd209b961e067e4dee07843efaf743cf438/text/104-validation-on-publish.md)
A frequently-requested feature (see [Wagtail issue #12505](https://github.com/wagtail/wagtail/issues/12505)) is the ability to save draft versions of pages in an incomplete state that would not pass validation, but still enforce validation at the point that the page is published or submitted for approval. This is also a prerequisite for an effective auto-save implementation, as noted in [RFC 99](https://github.com/wagtail/rfcs/pull/99). This RFC sets out the requirements for such a feature, and an approach to implementing it.

RFC 104: Validation on publish

---

text/107-roadmap-updates.md

[View the RFC in HTML](https://github.com/thibaudcolas/rfcs/blob/107-roadmap-updates/text/107-roadmap-updates.md). Once reviewed with enough feedback and approved by the core team, those changes will go live on the [Wagtail Roadmap](https://wagtail.org/roadmap/).
Compared to previous roadmap updates,
- This adds a lot of proposed roadmap items that are low on details. Some of those have been in discussions lately but without necessarily having a definitive approach selected. They seem interesting to showcase nonetheless.
- I’ve added a list of proposed items that don’t seem like they should make the cut. They’re similarly low on details, have potential, but seem like they are either too narrow or too broad to fit on the roadmap.
---
7.1\* and 7.2\*: Provisional version numbers. See our …

RFC #107: Wagtail 7.1* and 7.2* roadmap updates
